apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: agones-allocator-tls
  namespace: agones-system
spec:
  commonName: __IP_ADDRESS__
  ipAddresses:
    - __IP_ADDRESS__
  secretName: allocator-tls
  issuerRef:
    name: agones-self-signed
    kind: ClusterIssuer
